### ISSUE TITLE
Error on "meteor add std:react-accounts-ui-material-ui"?

### ISSUE THREAD

**Issue by VikR0001** [studiointeract/accounts-material#2]
running:

`meteor add std:react-accounts-ui-material-ui`

...brings up an error message:

> While adding package std:react-accounts-ui-material-ui:
> error: no such package
> 
>  $ meteor add std:react-accounts-ui-material-ui
>  => Errors while parsing arguments:           
> 
> While adding package std:react-accounts-ui-material-ui:
> error: no such package

**Comment by VikR0001** [comment]
Oh I see-- this package is pending official release.

**Comment by timbrandin** [comment]
Yeah, I have a friend who was supposed to work on this this weekend, but had other work to do, I'll probably do it myself next week. Feel free to get started with this, the integration is really lightweight, check the semantic package for instance. 💃
