### ISSUE TITLE
Error Adding std:accounts-material?

### ISSUE THREAD

**Issue by VikR0001** [studiointeract/accounts-material#4]
I'm looking forward to installing this. 

When I run:

> meteor add std:accounts-material

...I get the following:

>  => Errors while parsing arguments:           
> 
> While adding package std:accounts-material:
> error: no such package

How can I correct this?

**Comment by lawrentiy** [comment]
I suggest,  @timbrandin will read that issue and add std:accounts-material into Atmosphere index.
@VikR0001 , now before that you can just download that repo, add source to packages folder and that`s it.

**Comment by VikR0001** [comment]
Awesome. Thanks very much!

**Comment by timbrandin** [comment]
Sorry haven't had time to publish, will do it now. // T

2016-05-13 18:38 GMT+02:00 VikR0001 notifications@github.com:

> Awesome. Thanks very much!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/studiointeract/accounts-material/issues/4#issuecomment-219095212

## 

Cheers,
// Tim Brandin @timbrandin https://twitter.com/#!/timbrandin
http://timbrandin.com
http://studiointeract.com

**Comment by timbrandin** [comment]
It's deployed now, sorry once again.

**Comment by VikR0001** [comment]
Great!
