### ISSUE TITLE
facebook login isn't visible

### ISSUE THREAD

**Issue by romaluca** [studiointeract/accounts-material#6]
Hi, in my application i use the login with password + the facebook login.
If i use 
`https://github.com/studiointeract/accounts-basic`
the facebook login button appears in the login form. But if i use this plugin instead of the other, the facebook button doesn't appear.
I have to use this plugin beacuse i'm using materialize but i need also of the facebook login button.
What i have to do?

Thanks!

**Comment by sunlee-newyork** [comment]
+1

**Comment by fIa5h** [comment]
+1
